<?php
    if(!isset($_COOKIE['user'])){
        header('Location: /comp1230/assignments/assignment4/');
    }
    require('view/inc/header.inc.phtml');
?>
<div class="container d-flex flex-column align-items-center pt-5">
    <h1 class='text-center'>Add Client Notification</h1>
    <?php if($notify_message == "Error occurred. Please try again"):?>
      <h4 class='text-center text-danger'><?= $notify_message ?></h4>
    <?php else:?>
      <h4 class='text-center text-success'><?= $notify_message ?></h4>
    <?php endif;?>
    <?php ?>
    
    <form class='col-6' method='POST'>
        <div class="form-group mt-4 mx-2">
            <label for="client-id">Client ID: <span class='text-danger fw-bolder'>&#42;</span></label>
            <input type="text" class="form-control" name='client-id' value='<?=htmlspecialchars($_GET['clientId'])?>' readonly id="client-id" placeholder="Enter client ID">
        </div>

        <input type="hidden" class="form-control" name='notification-id' value='<?= $client_notificationId ?>'>

        <div class="form-group mt-4 mx-2">
        <label for="frequency">Frequency: <span class='text-danger fw-bolder'>&#42;</span></label>
        <select class="form-select" name="frequency" id="frequency" required>
          <?= $client_notification_frequency == '' ? "<option value='' selected disabled hidden>Select one</option>":"<option value='' disabled hidden>Select one</option>" ?>
          <?php foreach($frequencyList as $frequency):?>
              <?php if($client_notification_frequency == $frequency):?>
                  <?= "<option value='$frequency' selected>$frequency</option>"?>
              <?php else:?>
                  <?= "<option value='$frequency'>$frequency</option>" ?>
              <?php endif ?>
          <?php endforeach ?>
        </select>
      </div>
      
      <div class="form-group mt-4 mx-2">
        <label for="client_notification_date">Start date: <span class='text-danger fw-bolder'>&#42;</span></label>
        <input type="date" id="client_notification_date" name="notification-date" required>
      </div>
      
      <div class="form-group mt-4 mx-2">
        <label for='active'>Active: </label>
            <?php if($client_notification_status == 'active'):?>
              <?= "<input type='radio' class='form-check-input' name='status' value='active' id='active' checked>" ?>
            <?php else:?>
              <?= "<input type='radio' class='form-check-input' name='status' value='active' id='active'>" ?>
            <?php endif;?>
        <span class='m-4'></span>
        <label for='inactive'>Inactive:</label>
        <?php if($client_notification_status == 'inactive'):?>
              <?= "<input type='radio' class='form-check-input' name='status' value='inactive' id='inactive' checked>" ?>
            <?php else:?>
              <?= "<input type='radio' class='form-check-input' name='status' value='inactive' id='inactive'>" ?>
            <?php endif;?>
      </div>
      <button name='add-client-notification-button' type="submit" class="btn btn-primary mt-4 mx-2">Submit</button>
    </form>
</div>