<?php
    require('view/inc/header.inc.phtml');
?>
<div class="container d-flex flex-column align-items-center justify-content-center p-5 ">
    <div class="form d-flex mb-3">
        <div class = 'mx-2'>
            <a class='btn btn-outline-primary' href='/comp1230/assignments/assignment4/?page=employeeNotification'>Employee Notification</a>
        </div>
        <div class = 'mx-2'>
            <a class='btn btn-danger' href='/comp1230/assignments/assignment4/?page=clientNotification'>Client Notification</a>
        </div>
        <hr>
    </div>

    <form class="search d-flex mt-3" action = 'search.php' method='GET'>
            <input type="hidden" name="page" value='searchClientNotification'>
            <input class="form-control mx-2" name='search_client_notification_status' placeholder="Search by status">
            <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>

    <table class="table table-hover">
        <thead>
            <tr>
                <?php foreach($notificationHeaders['client'] as $header): ?>
                    <th class='text-center text-danger' scope="col"><?= $header ?></th>
                <?php endforeach;?>
                <th scope="col" class='text-center text-danger' style='width:100px'>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php if($clientNotificationList != 'No result found'): ?>
                <?php foreach($clientNotificationList as $clientNotification):?>
                    <tr>
                        <td class='text-center'><?php echo $clientNotification['notification_id']?></td>
                        <td class='text-center'><?php echo $clientNotification['client_id']?></td>
                        <td class='text-center'><?php echo $clientNotification['date']?></td>
                        <td class='text-center'><?php echo $clientNotification['frequency']?></td>
                        <td class='text-center'><?php echo $clientNotification['status']?></td>
                        <td class='d-flex justify-content-start'>
                            <form class='mx-1' method='GET'>
                                <input type="hidden" name="page" value='updateClientNotification'>
                                <input type="hidden" name="client-notification-id" value='<?php echo $clientNotification['notification_id']?>'>
                                <input type="hidden" name="client-id" value='<?php echo $clientNotification['client_id']?>'>
                                <input type="hidden" name="client-notification-date" value='<?php echo $clientNotification['date']?>'>
                                <input type="hidden" name="client-notification-frequency" value='<?php echo $clientNotification['frequency']?>'>
                                <input type="hidden" name="client-notification-status" value='<?= $clientNotification['status']?>'>

                                <button name='update-client-notification-page' class="btn btn-success">Update</button>
                            </form>
                        
                            <form class='mx-1' method='GET'>
                                <input type="hidden" name="page" value='deleteClientNotification'>
                                <input type="hidden" name="delete-client-notification" value='<?= $clientNotification['notification_id']?>'>
                                <button class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                <?php endforeach;?>               
            <?php endif;?>
            
        </tbody>
    </table>
</div>