<?php
    if(!isset($_COOKIE['user'])){
        header('Location: /comp1230/assignments/assignment4/');
    }
    require('view/inc/header.inc.phtml');
?>
<div class="container d-flex flex-column align-items-center">
    <h1 class='text-center'>Update Client</h1>
    <?php if($notify_message == "Error occurred. Please try again"):?>
      <h4 class='text-center text-danger'><?= $notify_message ?></h4>
    <?php else:?>
      <h4 class='text-center text-success'><?= $notify_message ?></h4>
    <?php endif;?>
    <?php ?>
    
    <form class='col-6' method='POST'>
        <input type="hidden" name="client-id" value='<?= $clientId ?>'>
        <div class="form-group mt-4 mx-2">
            <label for="company">Company name: <span class='text-danger fw-bolder'>&#42;</span></label>
            <input type="text" class="form-control"  name='company' value='<?= $client_company ?>' id="company" placeholder="Enter company name" required>
        </div>

        <div class="form-group mt-4 mx-2">
            <label for="business-number">Business number: <span class='text-danger fw-bolder'>&#42;</span></label>
            <input type="text" class="form-control" name="business-number" value='<?= $client_businessNumber ?>' id="business-number" placeholder="Enter business number" required>
        </div>

      <div class="form-group mt-4 mx-2">
        <label for="first-name">First name: <span class='text-danger fw-bolder'>&#42;</span></label>
        <input type="text" class="form-control" name='first-name' value='<?= $client_firstName ?>' id="first-name" placeholder="Enter client's first name" required>
      </div>

      <div class="form-group mt-4 mx-2">
        <label for="last-name">Last name: <span class='text-danger fw-bolder'>&#42;</span></label>
        <input type="text" class="form-control" name='last-name' value='<?= $client_lastName ?>' id="last-name" placeholder="Enter client's last name" required>
      </div>

      <div class="form-group mt-4 mx-2">
        <label for="phone-number">Phone number: <span class='text-danger fw-bolder'>&#42;</span></label>
        <p class='text-danger'><?= $phone_error ?></p>
        <input type="text" class="form-control" name='phone-number' value='<?= $client_phoneNumber ?>' id="phone-number" placeholder="Enter client's phone number" required>
      </div>

      <div class="form-group mt-4 mx-2">
        <label for="cellphone">Cell phone: <span class='text-danger fw-bolder'>&#42;</span></label>
        <p class='text-danger'><?= $cellphone_error ?></p>
        <input type="text" class="form-control" name='cellphone' value='<?= $client_cellphone ?>' id="cellphone" placeholder="Enter client's cell phone" required>
      </div>

      <div class="form-group mt-4 mx-2">
        <label for="carrier">Carrier: <span class='text-danger fw-bolder'>&#42;</span></label>
        <select class="form-select" name="carrier" id="carrier" required>
          <?= $client_carrier == '' ? "<option value='' selected disabled hidden>Select one</option>":"<option value='' disabled hidden>Select one</option>" ?>
          <?php foreach(array_keys($carriers) as $carrier):?>
              <?php if($client_carrier == $carrier):?>
                  <?= "<option value='$carrier' selected>$carrier</option>"?>
              <?php else:?>
                  <?= "<option value='$carrier'>$carrier</option>" ?>
              <?php endif ?>
          <?php endforeach ?>
        </select>
        
      </div>

      <div class="form-group mt-4 mx-2">
        <label for="hst">HST number:</label>
        <input type="text" class="form-control" name='hst' value='<?= $client_hst ?>' id="hst" placeholder="Enter client's hst number">
      </div>

      <div class="form-group mt-4 mx-2">
        <label for="website">Website:</label>
        <input type="text" class="form-control" name='website' value='<?= $client_website ?>' id="website" placeholder="Enter client's website">
      </div>

      <div class="form-group mt-4 mx-2">
        <label for='active'>Active: </label>
            <?php if($client_status == 'active'):?>
              <?= "<input type='radio' class='form-check-input' name='status' value='active' id='active' checked>" ?>
            <?php else:?>
              <?= "<input type='radio' class='form-check-input' name='status' value='active' id='active'>" ?>
            <?php endif;?>
        <span class='m-4'></span>
        <label for='inactive'>Inactive:</label>
        <?php if($client_status == 'inactive'):?>
              <?= "<input type='radio' class='form-check-input' name='status' value='inactive' id='inactive' checked>" ?>
            <?php else:?>
              <?= "<input type='radio' class='form-check-input' name='status' value='inactive' id='inactive'>" ?>
            <?php endif;?>
      </div>
      
      <button name='update-client-button' type="submit" class="btn btn-primary mt-4 mx-2">Update</button>
    </form>
</div>