<div class="container">
    
    
    <?php 
        if($notify_message == "Deleted successfully"){
            echo "<h4 class= 'text-success'>$notify_message</h4>";
            echo "<a href='/comp1230/assignments/assignment4?page=employee'>Go back</a>";
        }else if($notify_message == "Error occurred. Please try again"){
            echo "<h4 class= 'text-danger'>$notify_message</h4>";
            echo "<a href='/comp1230/assignments/assignment4?page=employee'>Go back</a>";
        }else{
            echo "<div class='container d-flex'>
            <form method='POST'>
                <div class='form-group'>
                    <h3>Are you sure you want to delete this employee?</h3>
                </div>
                <input type='hidden' name='delete-employee-id' value='$employeeId'>
                <input class='btn btn-primary' type='submit' name='delete_employee_yes_button' value='Yes'>
                <a class='btn btn-danger' href='/comp1230/assignments/assignment4?page=employee'>No</a>
            </form>
        </div>";
        }
    
    ?>
   
</div>