<header class='d-flex justify-between align-items-center'>
    <a class='col-1 nav-link' href='/comp1230/assignments/assignment4/'>
        <img src="view/images/logo.png" width='130' height='110' alt="logo">
    </a>
    <ul class='col nav justify-content-end px-5' style="font-size:20px;">
        <li class='nav-item'>
            <a class='nav-link' href='/comp1230/assignments/assignment4/'>Main</a>
        </li>
        <li class='nav-item'>
            <a class='nav-link' href='/comp1230/assignments/assignment4/?page=client'>Client</a>
        </li>
        <li class='nav-item'>
            <a class='nav-link' href='/comp1230/assignments/assignment4/?page=employee'>Employee</a>
        </li>
        <li class='nav-item'>
            <a class='nav-link' href='/comp1230/assignments/assignment4/?page=employeeNotification'>Notification</a>
        </li>
        <li class='nav-item'>
            <a class='nav-link' href='/comp1230/assignments/assignment4/?page=log'>Log</a>
        </li>
        <li class='nav-item'>
            <a class='nav-link' href='/comp1230/assignments/assignment4/?page=logout'>Logout</a>
        </li>
    </ul>
</header>