<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ABC FIRM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<style>
    body{
        <?php
            if($page == '' || $page == 'main' || $page == 'login' || $page == 'logout'){
                echo "background-image: url('./view/images/body_background.jpg');";
                echo "height: 100vh;";
            }else{
                echo "background-image: url('./view/images/client_background.png');";
                echo "height: auto;";
            }
        ?>
    width: auto;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    }
</style>
<body>
    