<p>Username: jamesbond@gmail.com</p>
<p>Password: 123456</p>
<div class="container h-75">
    <div class="row align-items-center h-100 justify-content-center">
        <div class="col-auto col-sm-auto col-md-6 col-lg-4 p-4">
            <div class="text-center pb-3">
                <img src="./view/images/logo.png" width='200' height='180' alt="logo">
            </div>
            <form method="POST">
                <div class="error col-12 mb-3 text-danger text-center"> 
                    <?= $notify_message ?>
                </div> 
                <div class="col-12 mb-3"> 
                    <input type="text" name='username' class="form-control" placeholder="Username" id="username">
                </div>
                
                <div class="mb-3">
                    <input type="password" name='password' placeholder="Password" class="form-control" id="password">
                </div>
                
                <button type="submit" name='login' class="btn btn-primary w-100">Login</button>
            </form>
            <hr style="color:black;">
            
            <div class="text-center my-2">
                <a href="#">Forgot password</a>
            </div>
            <div class=""></div>

            <div class="text-center my-2">
                Don't have an account?
                <a href="#"> Sign up</a>
            </div>
        </div>
    </div>
    
</div>