<div class="container">
    <div class="container d-flex">
        <form method='POST'>
            <div class="form-group">
                <h3>Are you sure you want to log out?</h3>
            </div>
            <input class='btn btn-primary' type="submit" name='logout_yes_button' value="Yes">
            <input class='btn btn-danger' type="submit" name='logout_no_button' value="No">
        </form>
    </div>
</div>