<?php
    require('view/inc/header.inc.phtml');
?>
<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class='text-center text-danger' scope="col">Student ID</th>
                <th class='text-center text-danger' scope="col" >Email Address</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class='text-center'>101293009</td>
                <td class='text-center'>Do.Huynh@georgebrown.ca</td>
            </tr>
        </tbody>
    </table>
</div>